version: '3.8'
services:
  coco-boot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coco-boot
    network_mode: "host"
    ports:
      - "8181:8181"
    environment:
      COCO_EXPIRATION_TTL: "5"
      COCO_REDIRECT_URI: ""
      COCO_CLIENT_ID: ""
      COCO_CLIENT_SECRET: ""
      COCO_AUTHORIZATION_ENDPOINT: ""
      COCO_TOKEN_ENDPOINT: ""
      COCO_USER_ENDPOINT: ""
      COCO_BASE_API: ""
      COCO_BASE_PROXY: ""
      COCO_FREQUENCY_TIME: "1"
      COCO_FREQUENCY_DEGREE: "8"
      COCO_USER_RATE_TIME: "5"
      COCO_USER_FREQUENCY_DEGREE: "1"
      COCO_USER_TOKEN_EXPIRE: "1"

  redis:
    image: redis
    container_name: coco-redis
    environment:
      # 设置时区
      - TZ=Asia/Shanghai
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
