name: Build and Push Docker Image

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - master

env:
  REGISTRY: ghcr.io
#  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/coco-boot
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-  

      - name: Check out code
        uses: actions/checkout@v2
#        with:
#          repository: ${{ github.repository }}
#          ref: ${{ github.ref }}
#          token: ${{ secrets.REPO_ACCESS_TOKEN }}
#          path: ${{ github.workspace }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/coco-boot:${{ github.ref_name }}
            ${{ secrets.DOCKERHUB_USERNAME }}/coco-boot:latest
